name: afg_sewing
description: "AFG Sewing Management Sytem"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  equatable: ^2.0.5
  uuid: ^4.4.2
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"  # or another color code
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:

  uses-material-design: true
  generate: true

  assets:
    - lang/
    - assets/images/
    - assets/images/yekhan/
    - assets/images/astin/
    - assets/icon/app_icon.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
